
/*
 * Copyright (c) 2008, Institute for Software Integrated Systems, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 *
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * @author Himanshu Neema
 * @author Harmon Nine
 */

// This code has been generated by the C2W code generator.
// Do not edit manually!

/*
 * 	NOTE:  ALL "if" STATEMENTS IN THIS CODE THAT HAD THE FORM:
 *
 *  if (condition) statement;
 *
 *	OR
 *
 *  if (condition) statement1;
 *  else           statement2;
 *
 *  HAVE BEEN CONVERTED TO THE FORMS:
 *
 *  if (condition) {
 *		statement;
 *	}
 *
 *	AND
 *
 *  if (condition) {
 *		statement1;
 *	} else {
 *		statement2;
 *	}
 *
 *	RESPECTIVELY.  THIS IS BECAUSE THE OMNET DEBUGGER APPEARS TO HAVE A PROBLEM
 *  WITH THE NON-BRACED FORMS OF THE IF STATEMENT.  *PLEASE* DO NOT CHANGE IT BACK.
 *  -- H.S.N.
 *
 */

#ifndef _StartIntegrityFirewall_CLASS
#define _StartIntegrityFirewall_CLASS

#include "OmnetCommand.hpp"
#include "C2WException.hpp"


class StartIntegrityFirewall : public OmnetCommand {

public:
	typedef OmnetCommand Super;
	typedef boost::shared_ptr< StartIntegrityFirewall > SP;

	static StringVector get_parameter_names() {
		return getDatamemberNames();
	}

	static StringVector get_all_parameter_names() {
		return getAllDatamemberNames();
	}

	StartIntegrityFirewall( void ) { }
	
	static SP create( void ) { return SP( new StartIntegrityFirewall ); }

private:
	
	
	static int &get_nodeFullPath_handle_var( void ) {
		static int nodeFullPath_handle;
		return nodeFullPath_handle;
	}
	static int &get_intMultiplier_handle_var( void ) {
		static int intMultiplier_handle;
		return intMultiplier_handle;
	}
	static int &get_doubleAdder_handle_var( void ) {
		static int doubleAdder_handle;
		return doubleAdder_handle;
	}
	static int &get_booleanEnableFlip_handle_var( void ) {
		static int booleanEnableFlip_handle;
		return booleanEnableFlip_handle;
	}
	static int &get_longMultiplier_handle_var( void ) {
		static int longMultiplier_handle;
		return longMultiplier_handle;
	}
	static int &get_doubleMultiplier_handle_var( void ) {
		static int doubleMultiplier_handle;
		return doubleMultiplier_handle;
	}
	static int &get_stringReplacement_handle_var( void ) {
		static int stringReplacement_handle;
		return stringReplacement_handle;
	}
	static int &get_longAdder_handle_var( void ) {
		static int longAdder_handle;
		return longAdder_handle;
	}
	static int &get_intAdder_handle_var( void ) {
		static int intAdder_handle;
		return intAdder_handle;
	}
	
public:
	
	
	static int get_nodeFullPath_handle( void ) { return get_nodeFullPath_handle_var(); }
	static int get_intMultiplier_handle( void ) { return get_intMultiplier_handle_var(); }
	static int get_doubleAdder_handle( void ) { return get_doubleAdder_handle_var(); }
	static int get_booleanEnableFlip_handle( void ) { return get_booleanEnableFlip_handle_var(); }
	static int get_longMultiplier_handle( void ) { return get_longMultiplier_handle_var(); }
	static int get_doubleMultiplier_handle( void ) { return get_doubleMultiplier_handle_var(); }
	static int get_stringReplacement_handle( void ) { return get_stringReplacement_handle_var(); }
	static int get_longAdder_handle( void ) { return get_longAdder_handle_var(); }
	static int get_intAdder_handle( void ) { return get_intAdder_handle_var(); }
	


private:
	static int &getHandle( void ) {
		static int handle;
		return handle;
	}

public:
	static int get_handle( void ) { return getHandle(); }
	static std::string get_class_name( void ) { return "StartIntegrityFirewall"; }

private:
	static StringVector &getDatamemberNames( void ) {
		static StringVector datamemberNames;
		return datamemberNames;
	}

	static StringVector &getAllDatamemberNames( void ) {
		static StringVector allDatamemberNames;
		return allDatamemberNames;
	}



private:

	static InteractionRoot::SP factory( void ) {
		return InteractionRoot::SP( new StartIntegrityFirewall() );
	}


	static std::string &getInitErrorMessage( void ) {
		static std::string initErrorMessage( "Error:  StartIntegrityFirewall:  could not initialize:  " );
		return initErrorMessage;
	}

protected:
	static void init( RTI::RTIambassador *rti );
	
private:
	static bool &getIsPublished( void ) {
		static bool isPublished = false;
		return isPublished;
	}
	
	static std::string &getPublishErrorMessage( void ) {
		static std::string publishErrorMessage = "Error:  StartIntegrityFirewall:  could not publish:  ";
		return publishErrorMessage;
	}
	
public:
	static void publish( RTI::RTIambassador *rti );
	
private:
	static std::string &getUnpublishErrorMessage( void ) {
		static std::string unpublishErrorMessage = "Error:  StartIntegrityFirewall:  could not unpublish:  ";
		return unpublishErrorMessage;
	}

public:
	static void unpublish( RTI::RTIambassador *rti );

private:
	static bool &getIsSubscribed( void ) {
		static bool isSubscribed = false;
		return isSubscribed;
	}
	static std::string &getSubscribeErrorMessage( void ) {
		static std::string subscribedErrorMessage = "Error:  StartIntegrityFirewall:  could not subscribe:  ";
		return subscribedErrorMessage;
	}

public:
	static void subscribe( RTI::RTIambassador *rti );
		
private:
	static std::string getUnsubscribeErrorMessage( void ) {
		static std::string unsubscribeErrorMessage = "Error:  StartIntegrityFirewall:  could not unsubscribe:  ";
		return unsubscribeErrorMessage;
	}
	
public:
	static void unsubscribe( RTI::RTIambassador *rti );
	
	static bool static_init( void );
	
	static bool match( int handle ) { return handle == get_handle(); }

	virtual int getClassHandle( void ) const { return get_handle(); }
	virtual std::string getClassName( void ) const { return get_class_name(); }
	virtual StringVector getParameterNames( void ) const { return get_parameter_names(); }
	virtual StringVector getAllParameterNames( void ) const { return get_all_parameter_names(); }

	virtual void publishInteraction( RTI::RTIambassador *rti ) { publish( rti ); }
	virtual void subscribeInteraction( RTI::RTIambassador *rti ) { subscribe( rti ); }

	virtual InteractionRoot::SP clone( void ) {
		return InteractionRoot::SP(  new StartIntegrityFirewall( *this )  );
	}







private:
	
	
	std::string _nodeFullPath;
	
	int _intMultiplier;
	
	double _doubleAdder;
	
	bool _booleanEnableFlip;
	
	long _longMultiplier;
	
	double _doubleMultiplier;
	
	std::string _stringReplacement;
	
	long _longAdder;
	
	int _intAdder;
	
public:
		
	void set_nodeFullPath( const std::string & nodeFullPath ) { _nodeFullPath = nodeFullPath; }
	const std::string & get_nodeFullPath( void ) const { return _nodeFullPath; }
	
	void set_intMultiplier( int intMultiplier ) { _intMultiplier = intMultiplier; }
	int get_intMultiplier( void ) const { return _intMultiplier; }
	
	void set_doubleAdder( double doubleAdder ) { _doubleAdder = doubleAdder; }
	double get_doubleAdder( void ) const { return _doubleAdder; }
	
	void set_booleanEnableFlip( bool booleanEnableFlip ) { _booleanEnableFlip = booleanEnableFlip; }
	bool get_booleanEnableFlip( void ) const { return _booleanEnableFlip; }
	
	void set_longMultiplier( long longMultiplier ) { _longMultiplier = longMultiplier; }
	long get_longMultiplier( void ) const { return _longMultiplier; }
	
	void set_doubleMultiplier( double doubleMultiplier ) { _doubleMultiplier = doubleMultiplier; }
	double get_doubleMultiplier( void ) const { return _doubleMultiplier; }
	
	void set_stringReplacement( const std::string & stringReplacement ) { _stringReplacement = stringReplacement; }
	const std::string & get_stringReplacement( void ) const { return _stringReplacement; }
	
	void set_longAdder( long longAdder ) { _longAdder = longAdder; }
	long get_longAdder( void ) const { return _longAdder; }
	
	void set_intAdder( int intAdder ) { _intAdder = intAdder; }
	int get_intAdder( void ) const { return _intAdder; }
	


	StartIntegrityFirewall( const RTI::ParameterHandleValuePairSet &datamemberMap ) : Super( datamemberMap ) { }
	
	StartIntegrityFirewall( const RTI::ParameterHandleValuePairSet &datamemberMap, const RTIfedTime &logicalTime ) : Super( datamemberMap, logicalTime ) { }
	
	
public:
	TypeMedley getParameter( const std::string &datamemberName ) const {
		
		
		if ( "nodeFullPath" == datamemberName ) {
			return TypeMedley( get_nodeFullPath() );
		}
		else if ( "intMultiplier" == datamemberName ) {
			return TypeMedley( get_intMultiplier() );
		}
		else if ( "doubleAdder" == datamemberName ) {
			return TypeMedley( get_doubleAdder() );
		}
		else if ( "booleanEnableFlip" == datamemberName ) {
			return TypeMedley( get_booleanEnableFlip() );
		}
		else if ( "longMultiplier" == datamemberName ) {
			return TypeMedley( get_longMultiplier() );
		}
		else if ( "doubleMultiplier" == datamemberName ) {
			return TypeMedley( get_doubleMultiplier() );
		}
		else if ( "stringReplacement" == datamemberName ) {
			return TypeMedley( get_stringReplacement() );
		}
		else if ( "longAdder" == datamemberName ) {
			return TypeMedley( get_longAdder() );
		}
		else if ( "intAdder" == datamemberName ) {
			return TypeMedley( get_intAdder() );
		} else {
			return Super::getParameter( datamemberName );
		}
	}
	
	TypeMedley getParameter( int datamemberHandle ) const {
		
		
		if ( get_nodeFullPath_handle() == datamemberHandle ) {
			return TypeMedley( get_nodeFullPath() );
		}
		else if ( get_intMultiplier_handle() == datamemberHandle ) {
			return TypeMedley( get_intMultiplier() );
		}
		else if ( get_doubleAdder_handle() == datamemberHandle ) {
			return TypeMedley( get_doubleAdder() );
		}
		else if ( get_booleanEnableFlip_handle() == datamemberHandle ) {
			return TypeMedley( get_booleanEnableFlip() );
		}
		else if ( get_longMultiplier_handle() == datamemberHandle ) {
			return TypeMedley( get_longMultiplier() );
		}
		else if ( get_doubleMultiplier_handle() == datamemberHandle ) {
			return TypeMedley( get_doubleMultiplier() );
		}
		else if ( get_stringReplacement_handle() == datamemberHandle ) {
			return TypeMedley( get_stringReplacement() );
		}
		else if ( get_longAdder_handle() == datamemberHandle ) {
			return TypeMedley( get_longAdder() );
		}
		else if ( get_intAdder_handle() == datamemberHandle ) {
			return TypeMedley( get_intAdder() );
		} else {
			return Super::getParameter( datamemberHandle );
		}
	}

protected:
	virtual bool setParameterAux( int param_handle, const std::string &val ) {
		bool retval = true;		
		
		
		if ( param_handle == get_nodeFullPath_handle() ) {
			set_nodeFullPath(  TypeMedley( val )  );
		}
		else if ( param_handle == get_intMultiplier_handle() ) {
			set_intMultiplier(  TypeMedley( val )  );
		}
		else if ( param_handle == get_doubleAdder_handle() ) {
			set_doubleAdder(  TypeMedley( val )  );
		}
		else if ( param_handle == get_booleanEnableFlip_handle() ) {
			set_booleanEnableFlip(  TypeMedley( val )  );
		}
		else if ( param_handle == get_longMultiplier_handle() ) {
			set_longMultiplier(  TypeMedley( val )  );
		}
		else if ( param_handle == get_doubleMultiplier_handle() ) {
			set_doubleMultiplier(  TypeMedley( val )  );
		}
		else if ( param_handle == get_stringReplacement_handle() ) {
			set_stringReplacement(  TypeMedley( val )  );
		}
		else if ( param_handle == get_longAdder_handle() ) {
			set_longAdder(  TypeMedley( val )  );
		}
		else if ( param_handle == get_intAdder_handle() ) {
			set_intAdder(  TypeMedley( val )  );
		} else {
			retval = Super::setParameterAux( param_handle, val );
		}
		return retval;
	}
	
	virtual bool setParameterAux( const std::string &datamemberName, const std::string &val ) {
		bool retval = true;
		
		
		if ( "nodeFullPath" == datamemberName ) {
			set_nodeFullPath(  TypeMedley( val )  );
		}
		else if ( "intMultiplier" == datamemberName ) {
			set_intMultiplier(  TypeMedley( val )  );
		}
		else if ( "doubleAdder" == datamemberName ) {
			set_doubleAdder(  TypeMedley( val )  );
		}
		else if ( "booleanEnableFlip" == datamemberName ) {
			set_booleanEnableFlip(  TypeMedley( val )  );
		}
		else if ( "longMultiplier" == datamemberName ) {
			set_longMultiplier(  TypeMedley( val )  );
		}
		else if ( "doubleMultiplier" == datamemberName ) {
			set_doubleMultiplier(  TypeMedley( val )  );
		}
		else if ( "stringReplacement" == datamemberName ) {
			set_stringReplacement(  TypeMedley( val )  );
		}
		else if ( "longAdder" == datamemberName ) {
			set_longAdder(  TypeMedley( val )  );
		}
		else if ( "intAdder" == datamemberName ) {
			set_intAdder(  TypeMedley( val )  );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}
		
		return retval;
	}
	
	virtual bool setParameterAux( const std::string &datamemberName, const TypeMedley &val ) {
		bool retval = true;
		
		
		if ( "nodeFullPath" == datamemberName ) {\
			set_nodeFullPath( val );
		}
		else if ( "intMultiplier" == datamemberName ) {\
			set_intMultiplier( val );
		}
		else if ( "doubleAdder" == datamemberName ) {\
			set_doubleAdder( val );
		}
		else if ( "booleanEnableFlip" == datamemberName ) {\
			set_booleanEnableFlip( val );
		}
		else if ( "longMultiplier" == datamemberName ) {\
			set_longMultiplier( val );
		}
		else if ( "doubleMultiplier" == datamemberName ) {\
			set_doubleMultiplier( val );
		}
		else if ( "stringReplacement" == datamemberName ) {\
			set_stringReplacement( val );
		}
		else if ( "longAdder" == datamemberName ) {\
			set_longAdder( val );
		}
		else if ( "intAdder" == datamemberName ) {\
			set_intAdder( val );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}
		
		return retval;
	}

	virtual ParameterHandleValuePairSetSP createDatamemberHandleValuePairSet( RTI::ULong count );

	virtual ParameterHandleValuePairSetSP createDatamemberHandleValuePairSet( ) {
		return createDatamemberHandleValuePairSet( 0 );
	}
	
	
};

typedef StartIntegrityFirewall::SP StartIntegrityFirewallSP;

static bool call_StartIntegrityFirewall_static_init = StartIntegrityFirewall::static_init();

std::ostream &operator<<( std::ostream &os, StartIntegrityFirewall::SP entitySP );
std::ostream &operator<<( std::ostream &os, const StartIntegrityFirewall &entity );
#endif
