// This code has been generated by the C2W code generator.
// Do not edit manually!

package MapperEx;

import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;

import c2w.hla.C2WInteractionRoot;
import c2w.hla.C2WLogger;
import c2w.hla.InteractionRoot;
import c2w.hla.SubscribedInteractionFilter;
import c2w.hla.SynchronizedFederate;


import c2w.hla.*;

public class ComplexMapperBase extends SynchronizedFederate {

	private SubscribedInteractionFilter _subscribedInteractionFilter = new SubscribedInteractionFilter();
	
	// constructor
	public ComplexMapperBase( String federation_id, String federate_id ) throws Exception {
	
		setLookahead( 0.2 );
		createRTI();
		joinFederation( federation_id, federate_id );

		enableTimeConstrained();

		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();
        // interaction pubsub
        
        NetworkPacket.publish( getRTI() );
        EUMoneyGram.publish( getRTI() );
        USMoneyGram.publish( getRTI() );
        IndianMoneyGram.publish( getRTI() );
        
        IndianMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			IndianMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);
        NetworkPacket.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			NetworkPacket.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);
        USMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			USMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);
        EUMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			EUMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);		
		// object pubsub
                        }
        
       // constructor
	public ComplexMapperBase(  String[] federationInfo ) throws Exception {

		setLookahead( 0.2 );
		createRTI();
		joinFederation( federationInfo[ 0 ], federationInfo[ 1 ] );

		String loglevel = null;
		if(federationInfo.length == 3)
			C2WLogger.init( federationInfo[ 2 ] );
		else if(federationInfo.length > 3)
			C2WLogger.init( federationInfo[ 2 ], federationInfo[ 3 ] );		
		
		if(federationInfo.length == 5)
			loglevel = federationInfo[ 4 ];

		enableTimeConstrained();
		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();

        // interaction pubsub

        NetworkPacket.publish( getRTI() );
        EUMoneyGram.publish( getRTI() );
        USMoneyGram.publish( getRTI() );
        IndianMoneyGram.publish( getRTI() );

        IndianMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			IndianMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);
        NetworkPacket.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			NetworkPacket.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);
        USMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			USMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);
        EUMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			EUMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.NON_SELF, 
			SubscribedInteractionFilter.SourceFedFilter.NON_MAPPER 
		);		// object pubsub
                		// enable pubsub log
		if(federationInfo.length  > 2) {
			
			NetworkPacket.enablePublishLog(
				"NetworkPacket",
				"ComplexMapper",
				"undefined",
				loglevel);
			EUMoneyGram.enablePublishLog(
				"EUMoneyGram",
				"ComplexMapper",
				"undefined",
				loglevel);
			USMoneyGram.enablePublishLog(
				"USMoneyGram",
				"ComplexMapper",
				"undefined",
				loglevel);
			IndianMoneyGram.enablePublishLog(
				"IndianMoneyGram",
				"ComplexMapper",
				"undefined",
				loglevel);
			
			IndianMoneyGram.enableSubscribeLog(
				"IndianMoneyGram",
				"ComplexMapper", 
				"undefined", 
				loglevel);
			NetworkPacket.enableSubscribeLog(
				"NetworkPacket",
				"ComplexMapper", 
				"undefined", 
				loglevel);
			USMoneyGram.enableSubscribeLog(
				"USMoneyGram",
				"ComplexMapper", 
				"undefined", 
				loglevel);
			EUMoneyGram.enableSubscribeLog(
				"EUMoneyGram",
				"ComplexMapper", 
				"undefined", 
				loglevel);	
			
			
		}
		
	}
	
	public NetworkPacket create_NetworkPacket() {
	   NetworkPacket interaction = new NetworkPacket();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public EUMoneyGram create_EUMoneyGram() {
	   EUMoneyGram interaction = new EUMoneyGram();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public USMoneyGram create_USMoneyGram() {
	   USMoneyGram interaction = new USMoneyGram();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public IndianMoneyGram create_IndianMoneyGram() {
	   IndianMoneyGram interaction = new IndianMoneyGram();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	@Override
	public void receiveInteraction(
	 int interactionClass, ReceivedInteraction theInteraction, byte[] userSuppliedTag
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction );
		if ( interactionRoot instanceof C2WInteractionRoot ) {
			
			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}
		
		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag );			
	}

	@Override
	public void receiveInteraction(
	 int interactionClass,
	 ReceivedInteraction theInteraction,
	 byte[] userSuppliedTag,
	 LogicalTime theTime,
	 EventRetractionHandle retractionHandle
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction, theTime );
		if ( interactionRoot instanceof C2WInteractionRoot ) {

			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}

		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag, theTime, retractionHandle );			
	}
}
