// This code has been generated by the C2W code generator.
// Do not edit manually!

package MapperEx;

import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;

import c2w.hla.C2WInteractionRoot;
import c2w.hla.C2WLogger;
import c2w.hla.InteractionRoot;
import c2w.hla.SubscribedInteractionFilter;
import c2w.hla.SynchronizedFederate;


import c2w.hla.*;

public class ICICIBankBase extends SynchronizedFederate {

	private SubscribedInteractionFilter _subscribedInteractionFilter = new SubscribedInteractionFilter();
	
	// constructor
	public ICICIBankBase( String federation_id, String federate_id ) throws Exception {
	
		setLookahead( 0.2 );
		createRTI();
		joinFederation( federation_id, federate_id );

		enableTimeConstrained();

		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();
        // interaction pubsub
        
        CurrentAssestsInBillionUSDs.publish( getRTI() );
        IndianMoneyGram.publish( getRTI() );
        Namaste.publish( getRTI() );
        IndianTransferReceipt.publish( getRTI() );
        
        IndianTransferReceipt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			IndianTransferReceipt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        Namaste.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			Namaste.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        IndianMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			IndianMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        MoodysAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			MoodysAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        FedRescue.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			FedRescue.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        BadDebt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			BadDebt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        StandardAndPoorsAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			StandardAndPoorsAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);		
		// object pubsub
                        }
        
       // constructor
	public ICICIBankBase(  String[] federationInfo ) throws Exception {

		setLookahead( 0.2 );
		createRTI();
		joinFederation( federationInfo[ 0 ], federationInfo[ 1 ] );

		String loglevel = null;
		if(federationInfo.length == 3)
			C2WLogger.init( federationInfo[ 2 ] );
		else if(federationInfo.length > 3)
			C2WLogger.init( federationInfo[ 2 ], federationInfo[ 3 ] );		
		
		if(federationInfo.length == 5)
			loglevel = federationInfo[ 4 ];

		enableTimeConstrained();
		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();

        // interaction pubsub

        CurrentAssestsInBillionUSDs.publish( getRTI() );
        IndianMoneyGram.publish( getRTI() );
        Namaste.publish( getRTI() );
        IndianTransferReceipt.publish( getRTI() );

        IndianTransferReceipt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			IndianTransferReceipt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        Namaste.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			Namaste.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        IndianMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			IndianMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        MoodysAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			MoodysAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        FedRescue.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			FedRescue.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        BadDebt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			BadDebt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        StandardAndPoorsAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			StandardAndPoorsAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);		// object pubsub
                		// enable pubsub log
		if(federationInfo.length  > 2) {
			
			CurrentAssestsInBillionUSDs.enablePublishLog(
				"CurrentAssestsInBillionUSDs",
				"ICICIBank",
				"NORMAL",
				loglevel);
			IndianMoneyGram.enablePublishLog(
				"IndianMoneyGram",
				"ICICIBank",
				"NORMAL",
				loglevel);
			Namaste.enablePublishLog(
				"Namaste",
				"ICICIBank",
				"NORMAL",
				loglevel);
			IndianTransferReceipt.enablePublishLog(
				"IndianTransferReceipt",
				"ICICIBank",
				"NORMAL",
				loglevel);
			
			IndianTransferReceipt.enableSubscribeLog(
				"IndianTransferReceipt",
				"ICICIBank", 
				"NORMAL", 
				loglevel);
			Namaste.enableSubscribeLog(
				"Namaste",
				"ICICIBank", 
				"NORMAL", 
				loglevel);
			IndianMoneyGram.enableSubscribeLog(
				"IndianMoneyGram",
				"ICICIBank", 
				"NORMAL", 
				loglevel);
			MoodysAnalysis.enableSubscribeLog(
				"MoodysAnalysis",
				"ICICIBank", 
				"NORMAL", 
				loglevel);
			FedRescue.enableSubscribeLog(
				"FedRescue",
				"ICICIBank", 
				"NORMAL", 
				loglevel);
			BadDebt.enableSubscribeLog(
				"BadDebt",
				"ICICIBank", 
				"NORMAL", 
				loglevel);
			StandardAndPoorsAnalysis.enableSubscribeLog(
				"StandardAndPoorsAnalysis",
				"ICICIBank", 
				"NORMAL", 
				loglevel);	
			
			
		}
		
	}
	
	public CurrentAssestsInBillionUSDs create_CurrentAssestsInBillionUSDs() {
	   CurrentAssestsInBillionUSDs interaction = new CurrentAssestsInBillionUSDs();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public IndianMoneyGram create_IndianMoneyGram() {
	   IndianMoneyGram interaction = new IndianMoneyGram();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public Namaste create_Namaste() {
	   Namaste interaction = new Namaste();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public IndianTransferReceipt create_IndianTransferReceipt() {
	   IndianTransferReceipt interaction = new IndianTransferReceipt();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	@Override
	public void receiveInteraction(
	 int interactionClass, ReceivedInteraction theInteraction, byte[] userSuppliedTag
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction );
		if ( interactionRoot instanceof C2WInteractionRoot ) {
			
			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}
		
		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag );			
	}

	@Override
	public void receiveInteraction(
	 int interactionClass,
	 ReceivedInteraction theInteraction,
	 byte[] userSuppliedTag,
	 LogicalTime theTime,
	 EventRetractionHandle retractionHandle
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction, theTime );
		if ( interactionRoot instanceof C2WInteractionRoot ) {

			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}

		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag, theTime, retractionHandle );			
	}
}
