// This code has been generated by the C2W code generator.
// Do not edit manually!

package MapperEx;

import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;

import c2w.hla.C2WInteractionRoot;
import c2w.hla.C2WLogger;
import c2w.hla.InteractionRoot;
import c2w.hla.SubscribedInteractionFilter;
import c2w.hla.SynchronizedFederate;


import c2w.hla.*;

public class SocieteGeneraleBase extends SynchronizedFederate {

	private SubscribedInteractionFilter _subscribedInteractionFilter = new SubscribedInteractionFilter();
	
	// constructor
	public SocieteGeneraleBase( String federation_id, String federate_id ) throws Exception {
	
		setLookahead( 0.2 );
		createRTI();
		joinFederation( federation_id, federate_id );

		enableTimeConstrained();

		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();
        // interaction pubsub
        
        Bonjour.publish( getRTI() );
        FrenchTransferReceipt.publish( getRTI() );
        EUMoneyGram.publish( getRTI() );
        CurrentAssestsInBillionUSDs.publish( getRTI() );
        EUDebtSG.publish( getRTI() );
        
        FrenchTransferReceipt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			FrenchTransferReceipt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        StandardAndPoorsAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			StandardAndPoorsAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        FedRescue.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			FedRescue.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        MoodysAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			MoodysAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        EUMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			EUMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        BadDebt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			BadDebt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        Bonjour.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			Bonjour.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        EUDebtSG.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			EUDebtSG.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);		
		// object pubsub
                        }
        
       // constructor
	public SocieteGeneraleBase(  String[] federationInfo ) throws Exception {

		setLookahead( 0.2 );
		createRTI();
		joinFederation( federationInfo[ 0 ], federationInfo[ 1 ] );

		String loglevel = null;
		if(federationInfo.length == 3)
			C2WLogger.init( federationInfo[ 2 ] );
		else if(federationInfo.length > 3)
			C2WLogger.init( federationInfo[ 2 ], federationInfo[ 3 ] );		
		
		if(federationInfo.length == 5)
			loglevel = federationInfo[ 4 ];

		enableTimeConstrained();
		enableTimeRegulation( getLookahead() );
		enableAsynchronousDelivery();

        // interaction pubsub

        Bonjour.publish( getRTI() );
        FrenchTransferReceipt.publish( getRTI() );
        EUMoneyGram.publish( getRTI() );
        CurrentAssestsInBillionUSDs.publish( getRTI() );
        EUDebtSG.publish( getRTI() );

        FrenchTransferReceipt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			FrenchTransferReceipt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        StandardAndPoorsAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			StandardAndPoorsAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        FedRescue.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			FedRescue.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        MoodysAnalysis.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			MoodysAnalysis.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        EUMoneyGram.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			EUMoneyGram.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        BadDebt.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			BadDebt.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.SOURCE_FILTER_DISABLED 
		);
        Bonjour.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			Bonjour.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);
        EUDebtSG.subscribe( getRTI() );
        _subscribedInteractionFilter.setFedFilters( 
			EUDebtSG.get_handle(), 
			SubscribedInteractionFilter.OriginFedFilter.ORIGIN_FILTER_DISABLED, 
			SubscribedInteractionFilter.SourceFedFilter.MAPPER 
		);		// object pubsub
                		// enable pubsub log
		if(federationInfo.length  > 2) {
			
			Bonjour.enablePublishLog(
				"Bonjour",
				"SocieteGenerale",
				"NORMAL",
				loglevel);
			FrenchTransferReceipt.enablePublishLog(
				"FrenchTransferReceipt",
				"SocieteGenerale",
				"NORMAL",
				loglevel);
			EUMoneyGram.enablePublishLog(
				"EUMoneyGram",
				"SocieteGenerale",
				"NORMAL",
				loglevel);
			CurrentAssestsInBillionUSDs.enablePublishLog(
				"CurrentAssestsInBillionUSDs",
				"SocieteGenerale",
				"NORMAL",
				loglevel);
			EUDebtSG.enablePublishLog(
				"EUDebtSG",
				"SocieteGenerale",
				"NORMAL",
				loglevel);
			
			FrenchTransferReceipt.enableSubscribeLog(
				"FrenchTransferReceipt",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			StandardAndPoorsAnalysis.enableSubscribeLog(
				"StandardAndPoorsAnalysis",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			FedRescue.enableSubscribeLog(
				"FedRescue",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			MoodysAnalysis.enableSubscribeLog(
				"MoodysAnalysis",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			EUMoneyGram.enableSubscribeLog(
				"EUMoneyGram",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			BadDebt.enableSubscribeLog(
				"BadDebt",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			Bonjour.enableSubscribeLog(
				"Bonjour",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);
			EUDebtSG.enableSubscribeLog(
				"EUDebtSG",
				"SocieteGenerale", 
				"NORMAL", 
				loglevel);	
			
			
		}
		
	}
	
	public Bonjour create_Bonjour() {
	   Bonjour interaction = new Bonjour();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public FrenchTransferReceipt create_FrenchTransferReceipt() {
	   FrenchTransferReceipt interaction = new FrenchTransferReceipt();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public EUMoneyGram create_EUMoneyGram() {
	   EUMoneyGram interaction = new EUMoneyGram();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public CurrentAssestsInBillionUSDs create_CurrentAssestsInBillionUSDs() {
	   CurrentAssestsInBillionUSDs interaction = new CurrentAssestsInBillionUSDs();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	public EUDebtSG create_EUDebtSG() {
	   EUDebtSG interaction = new EUDebtSG();
	   interaction.set_sourceFed( getFederateId() );
	   interaction.set_originFed( getFederateId() );
	   return interaction;
	}
	@Override
	public void receiveInteraction(
	 int interactionClass, ReceivedInteraction theInteraction, byte[] userSuppliedTag
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction );
		if ( interactionRoot instanceof C2WInteractionRoot ) {
			
			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}
		
		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag );			
	}

	@Override
	public void receiveInteraction(
	 int interactionClass,
	 ReceivedInteraction theInteraction,
	 byte[] userSuppliedTag,
	 LogicalTime theTime,
	 EventRetractionHandle retractionHandle
	) {
		InteractionRoot interactionRoot = InteractionRoot.create_interaction( interactionClass, theInteraction, theTime );
		if ( interactionRoot instanceof C2WInteractionRoot ) {

			C2WInteractionRoot c2wInteractionRoot = (C2WInteractionRoot)interactionRoot;

	        // Filter interaction if src/origin fed requirements (if any) are not met
	        if (  _subscribedInteractionFilter.filterC2WInteraction( getFederateId(), c2wInteractionRoot )  ) {
	        	return;
	        } 
		}

		super.receiveInteraction( interactionClass, theInteraction, userSuppliedTag, theTime, retractionHandle );			
	}
}
