
// This code has been generated by the C2W code generator.
// Do not edit manually!

package TESDemoIntegrationModel;

import java.util.HashSet;
import java.util.Set;

import hla.rti.*;

import c2w.hla.*;

/**
* The StartIntegrityFirewall class implements the StartIntegrityFirewall interaction in the
* TESDemoIntegrationModel simulation.
*/
public class StartIntegrityFirewall extends OmnetCommand {

	/**
	* Default constructor -- creates an instance of the StartIntegrityFirewall interaction
	* class with default parameter values.
	*/
	public StartIntegrityFirewall() { }

	
	
	private static int _nodeFullPath_handle;
	private static int _intMultiplier_handle;
	private static int _doubleAdder_handle;
	private static int _booleanEnableFlip_handle;
	private static int _longMultiplier_handle;
	private static int _doubleMultiplier_handle;
	private static int _stringReplacement_handle;
	private static int _longAdder_handle;
	private static int _intAdder_handle;
	
	
	/**
	* Returns the handle (RTI assigned) of the "nodeFullPath" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "nodeFullPath" parameter
	*/
	public static int get_nodeFullPath_handle() { return _nodeFullPath_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "intMultiplier" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "intMultiplier" parameter
	*/
	public static int get_intMultiplier_handle() { return _intMultiplier_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "doubleAdder" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "doubleAdder" parameter
	*/
	public static int get_doubleAdder_handle() { return _doubleAdder_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "booleanEnableFlip" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "booleanEnableFlip" parameter
	*/
	public static int get_booleanEnableFlip_handle() { return _booleanEnableFlip_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "longMultiplier" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "longMultiplier" parameter
	*/
	public static int get_longMultiplier_handle() { return _longMultiplier_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "doubleMultiplier" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "doubleMultiplier" parameter
	*/
	public static int get_doubleMultiplier_handle() { return _doubleMultiplier_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "stringReplacement" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "stringReplacement" parameter
	*/
	public static int get_stringReplacement_handle() { return _stringReplacement_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "longAdder" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "longAdder" parameter
	*/
	public static int get_longAdder_handle() { return _longAdder_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "intAdder" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "intAdder" parameter
	*/
	public static int get_intAdder_handle() { return _intAdder_handle; }
	
	
	
	private static boolean _isInitialized = false;

	private static int _handle;

	/**
	* Returns the handle (RTI assigned) of the StartIntegrityFirewall interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return the handle of the class pertaining to the reference,\
	* rather than the handle of the class for the instance referred to by the reference.
	* For the polymorphic version of this method, use {@link #getClassHandle()}.
	*/
	public static int get_handle() { return _handle; }

	/**
	* Returns the fully-qualified (dot-delimited) name of the StartIntegrityFirewall
	* interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return the name of the class pertaining to the reference,\
	* rather than the name of the class for the instance referred to by the reference.
	* For the polymorphic version of this method, use {@link #getClassName()}.
	*/
	public static String get_class_name() { return "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall"; }

	/**
	* Returns the simple name (the last name in the dot-delimited fully-qualified
	* class name) of the StartIntegrityFirewall interaction class.
	*/
	public static String get_simple_class_name() { return "StartIntegrityFirewall"; }

	private static Set< String > _datamemberNames = new HashSet< String >();
	private static Set< String > _allDatamemberNames = new HashSet< String >();

	/**
	* Returns a set containing the names of all of the non-hidden parameters in the
	* StartIntegrityFirewall interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return a set of parameter names pertaining to the reference,\
	* rather than the parameter names of the class for the instance referred to by
	* the reference.  For the polymorphic version of this method, use
	* {@link #getParameterNames()}.
	*/
	public static Set< String > get_parameter_names() {
		return new HashSet< String >( _datamemberNames );
	}


	/**
	* Returns a set containing the names of all of the parameters in the
	* StartIntegrityFirewall interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return a set of parameter names pertaining to the reference,\
	* rather than the parameter names of the class for the instance referred to by
	* the reference.  For the polymorphic version of this method, use
	* {@link #getParameterNames()}.
	*/
	public static Set< String > get_all_parameter_names() {
		return new HashSet< String >( _allDatamemberNames );
	}


	

	static {
		_classNameSet.add( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall" );
		_classNameClassMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall", StartIntegrityFirewall.class );
		
		_datamemberClassNameSetMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall", _datamemberNames );
		_allDatamemberClassNameSetMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall", _allDatamemberNames );

		
		
		_datamemberNames.add( "nodeFullPath" );
		_datamemberNames.add( "intMultiplier" );
		_datamemberNames.add( "doubleAdder" );
		
		
		_datamemberNames.add( "booleanEnableFlip" );
		_datamemberNames.add( "longMultiplier" );
		_datamemberNames.add( "doubleMultiplier" );
		
		_datamemberNames.add( "stringReplacement" );
		_datamemberNames.add( "longAdder" );
		_datamemberNames.add( "intAdder" );
		
		
		
		
		_allDatamemberNames.add( "nodeFullPath" );
		_allDatamemberNames.add( "intMultiplier" );
		_allDatamemberNames.add( "doubleAdder" );
		_allDatamemberNames.add( "sourceFed" );
		_allDatamemberNames.add( "uniqueCommandID" );
		_allDatamemberNames.add( "booleanEnableFlip" );
		_allDatamemberNames.add( "longMultiplier" );
		_allDatamemberNames.add( "doubleMultiplier" );
		_allDatamemberNames.add( "originFed" );
		_allDatamemberNames.add( "stringReplacement" );
		_allDatamemberNames.add( "longAdder" );
		_allDatamemberNames.add( "intAdder" );
		_allDatamemberNames.add( "federateFilter" );
		_allDatamemberNames.add( "actualLogicalGenerationTime" );
		
		
		_datamemberTypeMap.put( "nodeFullPath", "String" );
		_datamemberTypeMap.put( "intMultiplier", "int" );
		_datamemberTypeMap.put( "doubleAdder", "double" );
		_datamemberTypeMap.put( "booleanEnableFlip", "boolean" );
		_datamemberTypeMap.put( "longMultiplier", "long" );
		_datamemberTypeMap.put( "doubleMultiplier", "double" );
		_datamemberTypeMap.put( "stringReplacement", "String" );
		_datamemberTypeMap.put( "longAdder", "long" );
		_datamemberTypeMap.put( "intAdder", "int" );
	
	

	}


	private static String initErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall:  could not initialize:  ";
	protected static void init( RTIambassador rti ) {
		if ( _isInitialized ) return;
		_isInitialized = true;
		
		OmnetCommand.init( rti );
		
		boolean isNotInitialized = true;
		while( isNotInitialized ) {
			try {
				_handle = rti.getInteractionClassHandle( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall" );
				isNotInitialized = false;
			} catch ( FederateNotExecutionMember f ) {
				System.err.println( initErrorMessage + "Federate Not Execution Member" );
				f.printStackTrace();
				return;				
			} catch ( NameNotFound n ) {
				System.err.println( initErrorMessage + "Name Not Found" );
				n.printStackTrace();
				return;				
			} catch ( Exception e ) {
				e.printStackTrace();
				try { Thread.sleep( 50 ); } catch( Exception e1 ) { }					
			}
		}

		_classNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall", get_handle() );
		_classHandleNameMap.put( get_handle(), "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall" );
		_classHandleSimpleNameMap.put( get_handle(), "StartIntegrityFirewall" );

		
		isNotInitialized = true;
		while( isNotInitialized ) {
			try {
							
				_nodeFullPath_handle = rti.getParameterHandle( "nodeFullPath", get_handle() );			
				_intMultiplier_handle = rti.getParameterHandle( "intMultiplier", get_handle() );			
				_doubleAdder_handle = rti.getParameterHandle( "doubleAdder", get_handle() );			
				_booleanEnableFlip_handle = rti.getParameterHandle( "booleanEnableFlip", get_handle() );			
				_longMultiplier_handle = rti.getParameterHandle( "longMultiplier", get_handle() );			
				_doubleMultiplier_handle = rti.getParameterHandle( "doubleMultiplier", get_handle() );			
				_stringReplacement_handle = rti.getParameterHandle( "stringReplacement", get_handle() );			
				_longAdder_handle = rti.getParameterHandle( "longAdder", get_handle() );			
				_intAdder_handle = rti.getParameterHandle( "intAdder", get_handle() );
				isNotInitialized = false;
			} catch ( FederateNotExecutionMember f ) {
				System.err.println( initErrorMessage + "Federate Not Execution Member" );
				f.printStackTrace();
				return;				
			} catch ( InteractionClassNotDefined i ) {
				System.err.println( initErrorMessage + "Interaction Class Not Defined" );
				i.printStackTrace();
				return;				
			} catch ( NameNotFound n ) {
				System.err.println( initErrorMessage + "Name Not Found" );
				n.printStackTrace();
				return;				
			} catch ( Exception e ) {
				e.printStackTrace();
				try { Thread.sleep( 50 ); } catch( Exception e1 ) { }					
			}
		}
			
			
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,nodeFullPath", get_nodeFullPath_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,intMultiplier", get_intMultiplier_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,doubleAdder", get_doubleAdder_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,booleanEnableFlip", get_booleanEnableFlip_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,longMultiplier", get_longMultiplier_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,doubleMultiplier", get_doubleMultiplier_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,stringReplacement", get_stringReplacement_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,longAdder", get_longAdder_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall,intAdder", get_intAdder_handle() );
			
			
		_datamemberHandleNameMap.put( get_nodeFullPath_handle(), "nodeFullPath" );
		_datamemberHandleNameMap.put( get_intMultiplier_handle(), "intMultiplier" );
		_datamemberHandleNameMap.put( get_doubleAdder_handle(), "doubleAdder" );
		_datamemberHandleNameMap.put( get_booleanEnableFlip_handle(), "booleanEnableFlip" );
		_datamemberHandleNameMap.put( get_longMultiplier_handle(), "longMultiplier" );
		_datamemberHandleNameMap.put( get_doubleMultiplier_handle(), "doubleMultiplier" );
		_datamemberHandleNameMap.put( get_stringReplacement_handle(), "stringReplacement" );
		_datamemberHandleNameMap.put( get_longAdder_handle(), "longAdder" );
		_datamemberHandleNameMap.put( get_intAdder_handle(), "intAdder" );
		
	}


	private static boolean _isPublished = false;
	private static String publishErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall:  could not publish:  ";

	/**
	* Publishes the StartIntegrityFirewall interaction class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void publish( RTIambassador rti ) {
		if ( _isPublished ) return;
		
		init( rti );

	

		synchronized( rti ) {
			boolean isNotPublished = true;
			while( isNotPublished ) {
				try {
					rti.publishInteractionClass( get_handle() );
					isNotPublished = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( publishErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( publishErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isPublished = true;
	}

	private static String unpublishErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall:  could not unpublish:  ";
	/**
	* Unpublishes the StartIntegrityFirewall interaction class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void unpublish( RTIambassador rti ) {
		if ( !_isPublished ) return;
		
		init( rti );
		synchronized( rti ) {
			boolean isNotUnpublished = true;
			while( isNotUnpublished ) {
				try {
					rti.unpublishInteractionClass( get_handle() );
					isNotUnpublished = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( unpublishErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( unpublishErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( InteractionClassNotPublished i ) {
					System.err.println( unpublishErrorMessage + "Interaction Class Not Published" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isPublished = false;
	}

	private static boolean _isSubscribed = false;
	private static String subscribeErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall:  could not subscribe:  ";
	/**
	* Subscribes a federate to the StartIntegrityFirewall interaction class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void subscribe( RTIambassador rti ) {
		if ( _isSubscribed ) return;
		
		init( rti );
	
		
		synchronized( rti ) {
			boolean isNotSubscribed = true;
			while( isNotSubscribed ) {
				try {
					rti.subscribeInteractionClass( get_handle() );
					isNotSubscribed = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( subscribeErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( subscribeErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isSubscribed = true;
	}

	private static String unsubscribeErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ActionBase.OmnetCommand.StartIntegrityFirewall:  could not unsubscribe:  ";
	/**
	* Unsubscribes a federate from the StartIntegrityFirewall interaction class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void unsubscribe( RTIambassador rti ) {
		if ( !_isSubscribed ) return;

		init( rti );
		synchronized( rti ) {
			boolean isNotUnsubscribed = true;
			while( isNotUnsubscribed ) {
				try {
					rti.unsubscribeInteractionClass( get_handle() );
					isNotUnsubscribed = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( unsubscribeErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( unsubscribeErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( InteractionClassNotSubscribed i ) {
					System.err.println( unsubscribeErrorMessage + "Interaction Class Not Subscribed" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isSubscribed = false;
	}

	/**
	* Return true if "handle" is equal to the handle (RTI assigned) of this class
	* (that is, the StartIntegrityFirewall interaction class).
	*
	* @param handle handle to compare to the value of the handle (RTI assigned) of
	* this class (the StartIntegrityFirewall interaction class).
	* @return "true" if "handle" matches the value of the handle of this class
	* (that is, the StartIntegrityFirewall interaction class).
	*/
	public static boolean match( int handle ) { return handle == get_handle(); }

	/**
	* Returns the handle (RTI assigned) of this instance's interaction class .
	* 
	* @return the handle (RTI assigned) if this instance's interaction class
	*/
	public int getClassHandle() { return get_handle(); }

	/**
	* Returns the fully-qualified (dot-delimited) name of this instance's interaction class.
	* 
	* @return the fully-qualified (dot-delimited) name of this instance's interaction class
	*/
	public String getClassName() { return get_class_name(); }

	/**
	* Returns the simple name (last name in its fully-qualified dot-delimited name)
	* of this instance's interaction class.
	* 
	* @return the simple name of this instance's interaction class 
	*/
	public String getSimpleClassName() { return get_simple_class_name(); }

	/**
	* Returns a set containing the names of all of the non-hiddenparameters of an
	* interaction class instance.
	*
	* @return set containing the names of all of the parameters of an
	* interaction class instance
	*/
	public Set< String > getParameterNames() { return get_parameter_names(); }

	/**
	* Returns a set containing the names of all of the parameters of an
	* interaction class instance.
	*
	* @return set containing the names of all of the parameters of an
	* interaction class instance
	*/
	public Set< String > getAllParameterNames() { return get_all_parameter_names(); }

	/**
	* Publishes the interaction class of this instance of the class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void publishInteraction( RTIambassador rti ) { publish( rti ); }

	/**
	* Unpublishes the interaction class of this instance of this class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void unpublishInteraction( RTIambassador rti ) { unpublish( rti ); }

	/**
	* Subscribes a federate to the interaction class of this instance of this class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void subscribeInteraction( RTIambassador rti ) { subscribe( rti ); }

	/**
	* Unsubscribes a federate from the interaction class of this instance of this class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void unsubscribeInteraction( RTIambassador rti ) { unsubscribe( rti ); }

	

	public String toString() {
		return "StartIntegrityFirewall("
			
			
			+ "nodeFullPath:" + get_nodeFullPath()
			+ "," + "intMultiplier:" + get_intMultiplier()
			+ "," + "doubleAdder:" + get_doubleAdder()
			+ "," + "booleanEnableFlip:" + get_booleanEnableFlip()
			+ "," + "longMultiplier:" + get_longMultiplier()
			+ "," + "doubleMultiplier:" + get_doubleMultiplier()
			+ "," + "stringReplacement:" + get_stringReplacement()
			+ "," + "longAdder:" + get_longAdder()
			+ "," + "intAdder:" + get_intAdder()
			+ ")";
	}
	



	
	
	private String _nodeFullPath = "";
	
	private int _intMultiplier = 0;
	
	private double _doubleAdder = 0;
	
	private boolean _booleanEnableFlip = false;
	
	private long _longMultiplier = 0;
	
	private double _doubleMultiplier = 0;
	
	private String _stringReplacement = "";
	
	private long _longAdder = 0;
	
	private int _intAdder = 0;

	
	
	/**
	* Set the value of the "nodeFullPath" parameter to "value" for this parameter.
	*
	* @param value the new value for the "nodeFullPath" parameter
	*/
	public void set_nodeFullPath( String value ) { _nodeFullPath = value; }
	
	/**
	* Returns the value of the "nodeFullPath" parameter of this interaction.
	*
	* @return the value of the "nodeFullPath" parameter
	*/
	public String get_nodeFullPath() { return _nodeFullPath; }
	
	
	/**
	* Set the value of the "intMultiplier" parameter to "value" for this parameter.
	*
	* @param value the new value for the "intMultiplier" parameter
	*/
	public void set_intMultiplier( int value ) { _intMultiplier = value; }
	
	/**
	* Returns the value of the "intMultiplier" parameter of this interaction.
	*
	* @return the value of the "intMultiplier" parameter
	*/
	public int get_intMultiplier() { return _intMultiplier; }
	
	
	/**
	* Set the value of the "doubleAdder" parameter to "value" for this parameter.
	*
	* @param value the new value for the "doubleAdder" parameter
	*/
	public void set_doubleAdder( double value ) { _doubleAdder = value; }
	
	/**
	* Returns the value of the "doubleAdder" parameter of this interaction.
	*
	* @return the value of the "doubleAdder" parameter
	*/
	public double get_doubleAdder() { return _doubleAdder; }
	
	
	/**
	* Set the value of the "booleanEnableFlip" parameter to "value" for this parameter.
	*
	* @param value the new value for the "booleanEnableFlip" parameter
	*/
	public void set_booleanEnableFlip( boolean value ) { _booleanEnableFlip = value; }
	
	/**
	* Returns the value of the "booleanEnableFlip" parameter of this interaction.
	*
	* @return the value of the "booleanEnableFlip" parameter
	*/
	public boolean get_booleanEnableFlip() { return _booleanEnableFlip; }
	
	
	/**
	* Set the value of the "longMultiplier" parameter to "value" for this parameter.
	*
	* @param value the new value for the "longMultiplier" parameter
	*/
	public void set_longMultiplier( long value ) { _longMultiplier = value; }
	
	/**
	* Returns the value of the "longMultiplier" parameter of this interaction.
	*
	* @return the value of the "longMultiplier" parameter
	*/
	public long get_longMultiplier() { return _longMultiplier; }
	
	
	/**
	* Set the value of the "doubleMultiplier" parameter to "value" for this parameter.
	*
	* @param value the new value for the "doubleMultiplier" parameter
	*/
	public void set_doubleMultiplier( double value ) { _doubleMultiplier = value; }
	
	/**
	* Returns the value of the "doubleMultiplier" parameter of this interaction.
	*
	* @return the value of the "doubleMultiplier" parameter
	*/
	public double get_doubleMultiplier() { return _doubleMultiplier; }
	
	
	/**
	* Set the value of the "stringReplacement" parameter to "value" for this parameter.
	*
	* @param value the new value for the "stringReplacement" parameter
	*/
	public void set_stringReplacement( String value ) { _stringReplacement = value; }
	
	/**
	* Returns the value of the "stringReplacement" parameter of this interaction.
	*
	* @return the value of the "stringReplacement" parameter
	*/
	public String get_stringReplacement() { return _stringReplacement; }
	
	
	/**
	* Set the value of the "longAdder" parameter to "value" for this parameter.
	*
	* @param value the new value for the "longAdder" parameter
	*/
	public void set_longAdder( long value ) { _longAdder = value; }
	
	/**
	* Returns the value of the "longAdder" parameter of this interaction.
	*
	* @return the value of the "longAdder" parameter
	*/
	public long get_longAdder() { return _longAdder; }
	
	
	/**
	* Set the value of the "intAdder" parameter to "value" for this parameter.
	*
	* @param value the new value for the "intAdder" parameter
	*/
	public void set_intAdder( int value ) { _intAdder = value; }
	
	/**
	* Returns the value of the "intAdder" parameter of this interaction.
	*
	* @return the value of the "intAdder" parameter
	*/
	public int get_intAdder() { return _intAdder; }
	


	protected StartIntegrityFirewall( ReceivedInteraction datamemberMap, boolean initFlag ) {
		super( datamemberMap, false );
		if ( initFlag ) setParameters( datamemberMap );
	}
	
	protected StartIntegrityFirewall( ReceivedInteraction datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
		super( datamemberMap, logicalTime, false );
		if ( initFlag ) setParameters( datamemberMap );
	}


	/**
	* Creates an instance of the StartIntegrityFirewall interaction class, using
	* "datamemberMap" to initialize its parameter values.
	* "datamemberMap" is usually acquired as an argument to an RTI federate
	* callback method, such as "receiveInteraction".
	*
	* @param datamemberMap data structure containing initial values for the
	* parameters of this new StartIntegrityFirewall interaction class instance
	*/
	public StartIntegrityFirewall( ReceivedInteraction datamemberMap ) {
		this( datamemberMap, true );
	}
	
	/**
	* Like {@link #StartIntegrityFirewall( ReceivedInteraction datamemberMap )}, except this
	* new StartIntegrityFirewall interaction class instance is given a timestamp of
	* "logicalTime".
	*
	* @param datamemberMap data structure containing initial values for the
	* parameters of this new StartIntegrityFirewall interaction class instance
	* @param logicalTime timestamp for this new StartIntegrityFirewall interaction class
	* instance
	*/
	public StartIntegrityFirewall( ReceivedInteraction datamemberMap, LogicalTime logicalTime ) {
		this( datamemberMap, logicalTime, true );
	}

	/**
	* Creates a new StartIntegrityFirewall interaction class instance that is a duplicate
	* of the instance referred to by StartIntegrityFirewall_var.
	*
	* @param StartIntegrityFirewall_var StartIntegrityFirewall interaction class instance of which
	* this newly created StartIntegrityFirewall interaction class instance will be a
	* duplicate
	*/
	public StartIntegrityFirewall( StartIntegrityFirewall StartIntegrityFirewall_var ) {
		super( StartIntegrityFirewall_var );
		
		
		set_nodeFullPath( StartIntegrityFirewall_var.get_nodeFullPath() );
		set_intMultiplier( StartIntegrityFirewall_var.get_intMultiplier() );
		set_doubleAdder( StartIntegrityFirewall_var.get_doubleAdder() );
		set_booleanEnableFlip( StartIntegrityFirewall_var.get_booleanEnableFlip() );
		set_longMultiplier( StartIntegrityFirewall_var.get_longMultiplier() );
		set_doubleMultiplier( StartIntegrityFirewall_var.get_doubleMultiplier() );
		set_stringReplacement( StartIntegrityFirewall_var.get_stringReplacement() );
		set_longAdder( StartIntegrityFirewall_var.get_longAdder() );
		set_intAdder( StartIntegrityFirewall_var.get_intAdder() );
	}


	/**
	* Returns the value of the parameter whose name is "datamemberName"
	* for this interaction.
	*
	* @param datamemberName name of parameter whose value is to be
	* returned
	* @return value of the parameter whose name is "datamemberName"
	* for this interaction
	*/
	public Object getParameter( String datamemberName ) {
		
		
		
		if (  "nodeFullPath".equals( datamemberName )  ) return get_nodeFullPath();
		else if (  "intMultiplier".equals( datamemberName )  ) return new Integer( get_intMultiplier() );
		else if (  "doubleAdder".equals( datamemberName )  ) return new Double( get_doubleAdder() );
		else if (  "booleanEnableFlip".equals( datamemberName )  ) return new Boolean( get_booleanEnableFlip() );
		else if (  "longMultiplier".equals( datamemberName )  ) return new Long( get_longMultiplier() );
		else if (  "doubleMultiplier".equals( datamemberName )  ) return new Double( get_doubleMultiplier() );
		else if (  "stringReplacement".equals( datamemberName )  ) return get_stringReplacement();
		else if (  "longAdder".equals( datamemberName )  ) return new Long( get_longAdder() );
		else if (  "intAdder".equals( datamemberName )  ) return new Integer( get_intAdder() );
		else return super.getParameter( datamemberName );
	}
	
	/**
	* Returns the value of the parameter whose handle (RTI assigned)
	* is "datamemberHandle" for this interaction.
	*
	* @param datamemberHandle handle (RTI assigned) of parameter whose
	* value is to be returned
	* @return value of the parameter whose handle (RTI assigned) is
	* "datamemberHandle" for this interaction
	*/
	public Object getParameter( int datamemberHandle ) {
		
				
		
		if ( get_nodeFullPath_handle() == datamemberHandle ) return get_nodeFullPath();
		else if ( get_intMultiplier_handle() == datamemberHandle ) return new Integer( get_intMultiplier() );
		else if ( get_doubleAdder_handle() == datamemberHandle ) return new Double( get_doubleAdder() );
		else if ( get_booleanEnableFlip_handle() == datamemberHandle ) return new Boolean( get_booleanEnableFlip() );
		else if ( get_longMultiplier_handle() == datamemberHandle ) return new Long( get_longMultiplier() );
		else if ( get_doubleMultiplier_handle() == datamemberHandle ) return new Double( get_doubleMultiplier() );
		else if ( get_stringReplacement_handle() == datamemberHandle ) return get_stringReplacement();
		else if ( get_longAdder_handle() == datamemberHandle ) return new Long( get_longAdder() );
		else if ( get_intAdder_handle() == datamemberHandle ) return new Integer( get_intAdder() );
		else return super.getParameter( datamemberHandle );
	}
	
	protected boolean setParameterAux( int param_handle, String val ) {
		boolean retval = true;		
		
			
		
		if ( param_handle == get_nodeFullPath_handle() ) set_nodeFullPath( val );
		else if ( param_handle == get_intMultiplier_handle() ) set_intMultiplier( Integer.parseInt( val ) );
		else if ( param_handle == get_doubleAdder_handle() ) set_doubleAdder( Double.parseDouble( val ) );
		else if ( param_handle == get_booleanEnableFlip_handle() ) set_booleanEnableFlip( Boolean.parseBoolean( val ) );
		else if ( param_handle == get_longMultiplier_handle() ) set_longMultiplier( Long.parseLong( val ) );
		else if ( param_handle == get_doubleMultiplier_handle() ) set_doubleMultiplier( Double.parseDouble( val ) );
		else if ( param_handle == get_stringReplacement_handle() ) set_stringReplacement( val );
		else if ( param_handle == get_longAdder_handle() ) set_longAdder( Long.parseLong( val ) );
		else if ( param_handle == get_intAdder_handle() ) set_intAdder( Integer.parseInt( val ) );
		else retval = super.setParameterAux( param_handle, val );
		
		return retval;
	}
	
	protected boolean setParameterAux( String datamemberName, String val ) {
		boolean retval = true;
		
			
		
		if (  "nodeFullPath".equals( datamemberName )  ) set_nodeFullPath( val );
		else if (  "intMultiplier".equals( datamemberName )  ) set_intMultiplier( Integer.parseInt( val ) );
		else if (  "doubleAdder".equals( datamemberName )  ) set_doubleAdder( Double.parseDouble( val ) );
		else if (  "booleanEnableFlip".equals( datamemberName )  ) set_booleanEnableFlip( Boolean.parseBoolean( val ) );
		else if (  "longMultiplier".equals( datamemberName )  ) set_longMultiplier( Long.parseLong( val ) );
		else if (  "doubleMultiplier".equals( datamemberName )  ) set_doubleMultiplier( Double.parseDouble( val ) );
		else if (  "stringReplacement".equals( datamemberName )  ) set_stringReplacement( val );
		else if (  "longAdder".equals( datamemberName )  ) set_longAdder( Long.parseLong( val ) );
		else if (  "intAdder".equals( datamemberName )  ) set_intAdder( Integer.parseInt( val ) );	
		else retval = super.setParameterAux( datamemberName, val );
		
		return retval;
	}
	
	protected boolean setParameterAux( String datamemberName, Object val ) {
		boolean retval = true;
		
		
		
		if (  "nodeFullPath".equals( datamemberName )  ) set_nodeFullPath( (String)val );
		else if (  "intMultiplier".equals( datamemberName )  ) set_intMultiplier( (Integer)val );
		else if (  "doubleAdder".equals( datamemberName )  ) set_doubleAdder( (Double)val );
		else if (  "booleanEnableFlip".equals( datamemberName )  ) set_booleanEnableFlip( (Boolean)val );
		else if (  "longMultiplier".equals( datamemberName )  ) set_longMultiplier( (Long)val );
		else if (  "doubleMultiplier".equals( datamemberName )  ) set_doubleMultiplier( (Double)val );
		else if (  "stringReplacement".equals( datamemberName )  ) set_stringReplacement( (String)val );
		else if (  "longAdder".equals( datamemberName )  ) set_longAdder( (Long)val );
		else if (  "intAdder".equals( datamemberName )  ) set_intAdder( (Integer)val );		
		else retval = super.setParameterAux( datamemberName, val );
		
		return retval;
	}

	protected SuppliedParameters createSuppliedDatamembers() {
		SuppliedParameters datamembers = super.createSuppliedDatamembers();

	
		
		
			datamembers.add( get_nodeFullPath_handle(), get_nodeFullPath().getBytes() );
		
			datamembers.add( get_intMultiplier_handle(), Integer.toString( get_intMultiplier() ).getBytes() );
		
			datamembers.add( get_doubleAdder_handle(), Double.toString( get_doubleAdder() ).getBytes() );
		
			datamembers.add( get_booleanEnableFlip_handle(), Boolean.toString( get_booleanEnableFlip() ).getBytes() );
		
			datamembers.add( get_longMultiplier_handle(), Long.toString( get_longMultiplier() ).getBytes() );
		
			datamembers.add( get_doubleMultiplier_handle(), Double.toString( get_doubleMultiplier() ).getBytes() );
		
			datamembers.add( get_stringReplacement_handle(), get_stringReplacement().getBytes() );
		
			datamembers.add( get_longAdder_handle(), Long.toString( get_longAdder() ).getBytes() );
		
			datamembers.add( get_intAdder_handle(), Integer.toString( get_intAdder() ).getBytes() );
		
	
		return datamembers;
	}

	
	public void copyFrom( Object object ) {
		super.copyFrom( object );
		if ( object instanceof StartIntegrityFirewall ) {
			StartIntegrityFirewall data = (StartIntegrityFirewall)object;
			
			
				_nodeFullPath = data._nodeFullPath;
				_intMultiplier = data._intMultiplier;
				_doubleAdder = data._doubleAdder;
				_booleanEnableFlip = data._booleanEnableFlip;
				_longMultiplier = data._longMultiplier;
				_doubleMultiplier = data._doubleMultiplier;
				_stringReplacement = data._stringReplacement;
				_longAdder = data._longAdder;
				_intAdder = data._intAdder;
			
		}
	}
}
