// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

/*
 * Copyright (c) 2008, Institute for Software Integrated Systems, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 *
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 */

/*
 * 	NOTE:  ALL "if" STATEMENTS IN THIS CODE THAT HAD THE FORM:
 *
 *  if (condition) statement;
 *
 *	OR
 *
 *  if (condition) statement1;
 *  else           statement2;
 *
 *  HAVE BEEN CONVERTED TO THE FORMS:
 *
 *  if (condition) {
 *		statement;
 *	}
 *
 *	AND
 *
 *  if (condition) {
 *		statement1;
 *	} else {
 *		statement2;
 *	}
 *
 *	RESPECTIVELY.  THIS IS BECAUSE THE OMNET DEBUGGER APPEARS TO HAVE A PROBLEM
 *  WITH THE NON-BRACED FORMS OF THE IF STATEMENT.  *PLEASE* DO NOT CHANGE IT BACK.
 *  -- H.S.N.
 *
 */

#ifndef _SimLog_CLASS
#define _SimLog_CLASS

#include "C2WInteractionRoot.hpp"
#include "C2WException.hpp"

class SimLog : public C2WInteractionRoot {
public:
	typedef C2WInteractionRoot Super;
	typedef boost::shared_ptr< SimLog > SP;

	static StringVector get_parameter_names() {
		return getDatamemberNames();
	}

	static StringVector get_all_parameter_names() {
		return getAllDatamemberNames();
	}

	SimLog( void ) { }

	static SP create( void ) { return SP( new SimLog ); }

private:
	static int &get_Comment_handle_var( void ) {
		static int Comment_handle;
		return Comment_handle;
	}

	static int &get_FedName_handle_var( void ) {
		static int FedName_handle;
		return FedName_handle;
	}

	static int &get_Time_handle_var( void ) {
		static int Time_handle;
		return Time_handle;
	}

	static int &get_actualLogicalGenerationTime_handle_var( void ) {
		static int actualLogicalGenerationTime_handle;
		return actualLogicalGenerationTime_handle;
	}

	static int &get_federateFilter_handle_var( void ) {
		static int federateFilter_handle;
		return federateFilter_handle;
	}

	static int &get_originFed_handle_var( void ) {
		static int originFed_handle;
		return originFed_handle;
	}

	static int &get_sourceFed_handle_var( void ) {
		static int sourceFed_handle;
		return sourceFed_handle;
	}

public:
	static int get_Comment_handle( void ) { return get_Comment_handle_var(); }
	static int get_FedName_handle( void ) { return get_FedName_handle_var(); }
	static int get_Time_handle( void ) { return get_Time_handle_var(); }
	static int get_actualLogicalGenerationTime_handle( void ) { return get_actualLogicalGenerationTime_handle_var(); }
	static int get_federateFilter_handle( void ) { return get_federateFilter_handle_var(); }
	static int get_originFed_handle( void ) { return get_originFed_handle_var(); }
	static int get_sourceFed_handle( void ) { return get_sourceFed_handle_var(); }

private:
	static int &getHandle( void ) {
		static int handle;
		return handle;
	}

public:
	static int get_handle( void ) { return getHandle(); }
	static std::string get_class_name( void ) { return "SimLog"; }

private:
	static StringVector &getDatamemberNames( void ) {
		static StringVector datamemberNames;
		return datamemberNames;
	}

	static StringVector &getAllDatamemberNames( void ) {
		static StringVector allDatamemberNames;
		return allDatamemberNames;
	}

private:
	static InteractionRoot::SP factory( void ) {
		return InteractionRoot::SP( new SimLog() );
	}

	static std::string &getInitErrorMessage( void ) {
		static std::string initErrorMessage( "Error:  SimLog:  could not initialize:  " );
		return initErrorMessage;
	}

protected:
	static void init( RTI::RTIambassador *rti );

private:
	static bool &getIsPublished( void ) {
		static bool isPublished = false;
		return isPublished;
	}

	static std::string &getPublishErrorMessage( void ) {
		static std::string publishErrorMessage = "Error:  SimLog:  could not publish:  ";
		return publishErrorMessage;
	}

public:
	static void publish( RTI::RTIambassador *rti );

private:
	static std::string &getUnpublishErrorMessage( void ) {
		static std::string unpublishErrorMessage = "Error:  SimLog:  could not unpublish:  ";
		return unpublishErrorMessage;
	}

public:
	static void unpublish( RTI::RTIambassador *rti );

private:
	static bool &getIsSubscribed( void ) {
		static bool isSubscribed = false;
		return isSubscribed;
	}
	static std::string &getSubscribeErrorMessage( void ) {
		static std::string subscribedErrorMessage = "Error:  SimLog:  could not subscribe:  ";
		return subscribedErrorMessage;
	}

public:
	static void subscribe( RTI::RTIambassador *rti );

private:
	static std::string getUnsubscribeErrorMessage( void ) {
		static std::string unsubscribeErrorMessage = "Error:  SimLog:  could not unsubscribe:  ";
		return unsubscribeErrorMessage;
	}

public:
	static void unsubscribe( RTI::RTIambassador *rti );

	static bool static_init( void );

	static bool match( int handle ) { return handle == get_handle(); }

	virtual int getClassHandle( void ) const { return get_handle(); }
	virtual std::string getClassName( void ) const { return get_class_name(); }
	virtual StringVector getParameterNames( void ) const { return get_parameter_names(); }
	virtual StringVector getAllParameterNames( void ) const { return get_all_parameter_names(); }

	virtual std::string getParameterName( int datamemberHandle ) const {
		if (datamemberHandle == get_Comment_handle()) {
			return std::string("Comment");
		} else if (datamemberHandle == get_FedName_handle()) {
			return std::string("FedName");
		} else if (datamemberHandle == get_Time_handle()) {
			return std::string("Time");
		} else if (datamemberHandle == get_actualLogicalGenerationTime_handle()) {
			return std::string("actualLogicalGenerationTime");
		} else if (datamemberHandle == get_federateFilter_handle()) {
			return std::string("federateFilter");
		} else if (datamemberHandle == get_originFed_handle()) {
			return std::string("originFed");
		} else if (datamemberHandle == get_sourceFed_handle()) {
			return std::string("sourceFed");
		} else {
			return C2WInteractionRoot::getParameterName(datamemberHandle);
		}
	}

	virtual void publishInteraction( RTI::RTIambassador *rti ) { publish( rti ); }
	virtual void subscribeInteraction( RTI::RTIambassador *rti ) { subscribe( rti ); }

	virtual InteractionRoot::SP clone( void ) {
		return InteractionRoot::SP(  new SimLog( *this )  );
	}

private:
	std::string _Comment;
	std::string _FedName;
	double _Time;

public:
	void set_Comment( const std::string & Comment ) { _Comment = Comment; }

	const std::string & get_Comment( void ) const { return _Comment; }

	void set_FedName( const std::string & FedName ) { _FedName = FedName; }

	const std::string & get_FedName( void ) const { return _FedName; }

	void set_Time( double Time ) { _Time = Time; }

	double get_Time( void ) const { return _Time; }

	SimLog( const RTI::ParameterHandleValuePairSet &datamemberMap ) : Super( datamemberMap ) { }

	SimLog( const RTI::ParameterHandleValuePairSet &datamemberMap, const RTIfedTime &logicalTime ) : Super( datamemberMap, logicalTime ) { }

public:
	TypeMedley getParameter( const std::string &datamemberName ) const {
		if ( "Comment" == datamemberName ) {
			return TypeMedley( get_Comment() );
		} else if ( "FedName" == datamemberName ) {
			return TypeMedley( get_FedName() );
		} else if ( "Time" == datamemberName ) {
			return TypeMedley( get_Time() );
		} else {
			return Super::getParameter( datamemberName );
		}
	}

protected:
	virtual bool setParameterAux( const std::string &datamemberName, const std::string &val ) {
		bool retval = true;
		if ( "Comment" == datamemberName ) {
			set_Comment(  TypeMedley( val )  );
		} else if ( "FedName" == datamemberName ) {
			set_FedName(  TypeMedley( val )  );
		} else if ( "Time" == datamemberName ) {
			set_Time(  TypeMedley( val )  );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}

		return retval;
	}

	virtual bool setParameterAux( const std::string &datamemberName, const TypeMedley &val ) {
		bool retval = true;
		if ( "Comment" == datamemberName ) {
			set_Comment( val );
		} else if ( "FedName" == datamemberName ) {
			set_FedName( val );
		} else if ( "Time" == datamemberName ) {
			set_Time( val );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}

		return retval;
	}
};

typedef SimLog::SP SimLogSP;

static bool call_SimLog_static_init = SimLog::static_init();

std::ostream &operator<<( std::ostream &os, SimLog::SP entitySP );
std::ostream &operator<<( std::ostream &os, const SimLog &entity );

#endif
