// This code has been generated by the C2W code generator.
// Do not edit manually!

package MapperEx;

import java.util.StringTokenizer;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;
import c2w.hla.*;

public class DataConversionMapper extends DataConversionMapperBase {

    private static Pattern pattern = Pattern.compile( "[^#]" );

	public DataConversionMapper(String federationId, String federateId)
			throws Exception {
		super(federationId, federateId);
	}

    public DataConversionMapper( String[] args ) throws Exception {
        super( args );
    }
    
    private static double STEP_EPSILON = 0.000001;
    
    public boolean isMapperFederate() {
        return true;
    }

    
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 620d4ad7_a097_f18b_2b93_06009ffdee5c) between interactions:
	//
	//         IndianTransferReceipt --to--> USTransferReceipt
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DataConversionMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_IndianTransferReceipt_to_USTransferReceipt_620d4ad7_a097_f18b_2b93_06009ffdee5c(IndianTransferReceipt i1) {
		
		return true;
	}


	public USTransferReceipt map_IndianTransferReceipt_to_USTransferReceipt_620d4ad7_a097_f18b_2b93_06009ffdee5c(IndianTransferReceipt i1) {
		USTransferReceipt o1 = create_USTransferReceipt();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: fa8ac4e8_6b26_84a8_1a8d_0f879d507ca5) between interactions:
	//
	//         FrenchTransferReceipt --to--> IndianTransferReceipt
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DataConversionMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_FrenchTransferReceipt_to_IndianTransferReceipt_fa8ac4e8_6b26_84a8_1a8d_0f879d507ca5(FrenchTransferReceipt i1) {
		
		return true;
	}


	public IndianTransferReceipt map_FrenchTransferReceipt_to_IndianTransferReceipt_fa8ac4e8_6b26_84a8_1a8d_0f879d507ca5(FrenchTransferReceipt i1) {
		IndianTransferReceipt o1 = create_IndianTransferReceipt();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 91ced97f_6d4b_b1ec_e9ea_95150d602844) between interactions:
	//
	//         FrenchTransferReceipt --to--> USTransferReceipt
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DataConversionMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_FrenchTransferReceipt_to_USTransferReceipt_91ced97f_6d4b_b1ec_e9ea_95150d602844(FrenchTransferReceipt i1) {
		
		return true;
	}


	public USTransferReceipt map_FrenchTransferReceipt_to_USTransferReceipt_91ced97f_6d4b_b1ec_e9ea_95150d602844(FrenchTransferReceipt i1) {
		USTransferReceipt o1 = create_USTransferReceipt();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 83ffcf08_9829_ccc0_a239_6f03b1ebd384) between interactions:
	//
	//         USTransferReceipt --to--> IndianTransferReceipt
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DataConversionMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_USTransferReceipt_to_IndianTransferReceipt_83ffcf08_9829_ccc0_a239_6f03b1ebd384(USTransferReceipt i1) {
		
		return true;
	}


	public IndianTransferReceipt map_USTransferReceipt_to_IndianTransferReceipt_83ffcf08_9829_ccc0_a239_6f03b1ebd384(USTransferReceipt i1) {
		IndianTransferReceipt o1 = create_IndianTransferReceipt();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: b7f143a0_7f9b_13e9_0102_1cf3e2b1d604) between interactions:
	//
	//         IndianTransferReceipt --to--> FrenchTransferReceipt
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DataConversionMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_IndianTransferReceipt_to_FrenchTransferReceipt_b7f143a0_7f9b_13e9_0102_1cf3e2b1d604(IndianTransferReceipt i1) {
		
		return true;
	}


	public FrenchTransferReceipt map_IndianTransferReceipt_to_FrenchTransferReceipt_b7f143a0_7f9b_13e9_0102_1cf3e2b1d604(IndianTransferReceipt i1) {
		FrenchTransferReceipt o1 = create_FrenchTransferReceipt();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 4a23508d_0647_0671_3f56_e68b2326bdc1) between interactions:
	//
	//         USTransferReceipt --to--> FrenchTransferReceipt
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DataConversionMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_USTransferReceipt_to_FrenchTransferReceipt_4a23508d_0647_0671_3f56_e68b2326bdc1(USTransferReceipt i1) {
		
		return true;
	}


	public FrenchTransferReceipt map_USTransferReceipt_to_FrenchTransferReceipt_4a23508d_0647_0671_3f56_e68b2326bdc1(USTransferReceipt i1) {
		FrenchTransferReceipt o1 = create_FrenchTransferReceipt();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
    
    
    
    

	
	public void execute() throws Exception {
	    double currentTime = 0;

	    AdvanceTimeRequest atr = new AdvanceTimeRequest( currentTime );
	    putAdvanceTimeRequest( atr );

	    readyToPopulate();
	    readyToRun();

	    startAdvanceTimeThread(TIME_ADVANCE_MODE.NEXT_EVENT_REQUEST_AVAILABLE);

	    while( true ) {
	    	System.out.print( "DataConversionMapper: Requesting RTI to proceed to (" + currentTime + ")..." );
	    	
	        atr.requestSyncStart();
	        currentTime = atr.getCurrentTime();

	        System.out.println( "granted!" );

	        InteractionRoot interactionRoot;

	        System.out.println("Now waiting to receive an interaction...");
	        while(  ( interactionRoot = getNextInteractionNoWait() ) != null ) {
	            	
				System.out.println( "DataConversionMapper: received interaction: \"" + interactionRoot + "\" at time: " + getCurrentTime() );

				boolean interactionMapped = false;			
				
				
				if( interactionRoot instanceof IndianTransferReceipt ) {
					IndianTransferReceipt i1 = (IndianTransferReceipt) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "USTransferReceipt".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_IndianTransferReceipt_to_USTransferReceipt_620d4ad7_a097_f18b_2b93_06009ffdee5c(i1) ) {
								USTransferReceipt o1 = map_IndianTransferReceipt_to_USTransferReceipt_620d4ad7_a097_f18b_2b93_06009ffdee5c(i1);
								System.out.println( "DataConversionMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof FrenchTransferReceipt ) {
					FrenchTransferReceipt i1 = (FrenchTransferReceipt) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "IndianTransferReceipt".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_FrenchTransferReceipt_to_IndianTransferReceipt_fa8ac4e8_6b26_84a8_1a8d_0f879d507ca5(i1) ) {
								IndianTransferReceipt o1 = map_FrenchTransferReceipt_to_IndianTransferReceipt_fa8ac4e8_6b26_84a8_1a8d_0f879d507ca5(i1);
								System.out.println( "DataConversionMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof FrenchTransferReceipt ) {
					FrenchTransferReceipt i1 = (FrenchTransferReceipt) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "USTransferReceipt".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_FrenchTransferReceipt_to_USTransferReceipt_91ced97f_6d4b_b1ec_e9ea_95150d602844(i1) ) {
								USTransferReceipt o1 = map_FrenchTransferReceipt_to_USTransferReceipt_91ced97f_6d4b_b1ec_e9ea_95150d602844(i1);
								System.out.println( "DataConversionMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof USTransferReceipt ) {
					USTransferReceipt i1 = (USTransferReceipt) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "IndianTransferReceipt".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_USTransferReceipt_to_IndianTransferReceipt_83ffcf08_9829_ccc0_a239_6f03b1ebd384(i1) ) {
								IndianTransferReceipt o1 = map_USTransferReceipt_to_IndianTransferReceipt_83ffcf08_9829_ccc0_a239_6f03b1ebd384(i1);
								System.out.println( "DataConversionMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof IndianTransferReceipt ) {
					IndianTransferReceipt i1 = (IndianTransferReceipt) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "FrenchTransferReceipt".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_IndianTransferReceipt_to_FrenchTransferReceipt_b7f143a0_7f9b_13e9_0102_1cf3e2b1d604(i1) ) {
								FrenchTransferReceipt o1 = map_IndianTransferReceipt_to_FrenchTransferReceipt_b7f143a0_7f9b_13e9_0102_1cf3e2b1d604(i1);
								System.out.println( "DataConversionMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof USTransferReceipt ) {
					USTransferReceipt i1 = (USTransferReceipt) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "FrenchTransferReceipt".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_USTransferReceipt_to_FrenchTransferReceipt_4a23508d_0647_0671_3f56_e68b2326bdc1(i1) ) {
								FrenchTransferReceipt o1 = map_USTransferReceipt_to_FrenchTransferReceipt_4a23508d_0647_0671_3f56_e68b2326bdc1(i1);
								System.out.println( "DataConversionMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}

				if( !interactionMapped ) {
	          		System.out.println( "DataConversionMapper: Received unknown interaction: " + interactionRoot );
	           	}
	        }

	        currentTime = getCurrentTime() + 1 + STEP_EPSILON;
	        AdvanceTimeRequest newATR = new AdvanceTimeRequest( currentTime );
	        putAdvanceTimeRequest( newATR );
	        
	        atr.requestSyncEnd();
	        atr = newATR;
	    }
	}

	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
	    System.out.println( "DataConversionMapper federate starting" );
	    try {
	    	DataConversionMapper mapperFed = new DataConversionMapper( args );
	        mapperFed.execute();
	    } catch ( Exception e ) {
	        System.err.println( "Exception caught: " + e.getMessage() );
	        e.printStackTrace();
	    }
	}

}
