// This code has been generated by the C2W code generator.
// Do not edit manually!

package MapperEx;

import java.util.StringTokenizer;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import hla.rti.EventRetractionHandle;
import hla.rti.LogicalTime;
import hla.rti.ReceivedInteraction;
import c2w.hla.*;

public class DirectMapper extends DirectMapperBase {

    private static Pattern pattern = Pattern.compile( "[^#]" );

	public DirectMapper(String federationId, String federateId)
			throws Exception {
		super(federationId, federateId);
	}

    public DirectMapper( String[] args ) throws Exception {
        super( args );
    }
    
    private static double STEP_EPSILON = 0.000001;
    
    public boolean isMapperFederate() {
        return true;
    }

    
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 3af870c5_f83f_5b95_d564_432d660bed35) between interactions:
	//
	//         Namaste --to--> Hello
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DirectMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_Namaste_to_Hello_3af870c5_f83f_5b95_d564_432d660bed35(Namaste i1) {
		
		return true;
	}


	public Hello map_Namaste_to_Hello_3af870c5_f83f_5b95_d564_432d660bed35(Namaste i1) {
		Hello o1 = create_Hello();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 4f6a15d1_ce0a_15b2_4f6b_8e76908dd1c7) between interactions:
	//
	//         Namaste --to--> Bonjour
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DirectMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_Namaste_to_Bonjour_4f6a15d1_ce0a_15b2_4f6b_8e76908dd1c7(Namaste i1) {
		
		return true;
	}


	public Bonjour map_Namaste_to_Bonjour_4f6a15d1_ce0a_15b2_4f6b_8e76908dd1c7(Namaste i1) {
		Bonjour o1 = create_Bonjour();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: ef590b70_b120_905a_67dd_3853023db3b5) between interactions:
	//
	//         Hello --to--> Bonjour
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DirectMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_Hello_to_Bonjour_ef590b70_b120_905a_67dd_3853023db3b5(Hello i1) {
		
		return true;
	}


	public Bonjour map_Hello_to_Bonjour_ef590b70_b120_905a_67dd_3853023db3b5(Hello i1) {
		Bonjour o1 = create_Bonjour();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 09b590a0_b1a3_c38b_1674_744766af192f) between interactions:
	//
	//         Bonjour --to--> Hello
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DirectMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_Bonjour_to_Hello_09b590a0_b1a3_c38b_1674_744766af192f(Bonjour i1) {
		
		return true;
	}


	public Hello map_Bonjour_to_Hello_09b590a0_b1a3_c38b_1674_744766af192f(Bonjour i1) {
		Hello o1 = create_Hello();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: cdd75990_a765_dd89_7fe5_9dd3a5d9c4a9) between interactions:
	//
	//         Bonjour --to--> Namaste
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DirectMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_Bonjour_to_Namaste_cdd75990_a765_dd89_7fe5_9dd3a5d9c4a9(Bonjour i1) {
		
		return true;
	}


	public Namaste map_Bonjour_to_Namaste_cdd75990_a765_dd89_7fe5_9dd3a5d9c4a9(Bonjour i1) {
		Namaste o1 = create_Namaste();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
	///////////////////////////////////////////////////////////////////////////////////////
	//
	// For SimpleMappingConnection (ID: 713ac5d1_f9c2_4f97_6ec0_449bfb12e09b) between interactions:
	//
	//         Hello --to--> Namaste
	//
	// This SimpleMappingConnection is located at:
	//
	//         Mappings/DirectMapper
	//
	///////////////////////////////////////////////////////////////////////////////////////
	public boolean isGuardConditionMet_Hello_to_Namaste_713ac5d1_f9c2_4f97_6ec0_449bfb12e09b(Hello i1) {
		
		return true;
	}


	public Namaste map_Hello_to_Namaste_713ac5d1_f9c2_4f97_6ec0_449bfb12e09b(Hello i1) {
		Namaste o1 = create_Namaste();
		InteractionRoot o1IR = (InteractionRoot) o1;
	    
	    
		

		o1.set_originFed(i1.get_originFed());
		o1.set_actualLogicalGenerationTime(i1.get_actualLogicalGenerationTime());

		return o1;
	}
    
    
    
    
    

	
	public void execute() throws Exception {
	    double currentTime = 0;

	    AdvanceTimeRequest atr = new AdvanceTimeRequest( currentTime );
	    putAdvanceTimeRequest( atr );

	    readyToPopulate();
	    readyToRun();

	    startAdvanceTimeThread(TIME_ADVANCE_MODE.NEXT_EVENT_REQUEST_AVAILABLE);

	    while( true ) {
	    	System.out.print( "DirectMapper: Requesting RTI to proceed to (" + currentTime + ")..." );
	    	
	        atr.requestSyncStart();
	        currentTime = atr.getCurrentTime();

	        System.out.println( "granted!" );

	        InteractionRoot interactionRoot;

	        System.out.println("Now waiting to receive an interaction...");
	        while(  ( interactionRoot = getNextInteractionNoWait() ) != null ) {
	            	
				System.out.println( "DirectMapper: received interaction: \"" + interactionRoot + "\" at time: " + getCurrentTime() );

				boolean interactionMapped = false;			
				
				
				if( interactionRoot instanceof Namaste ) {
					Namaste i1 = (Namaste) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "Hello".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_Namaste_to_Hello_3af870c5_f83f_5b95_d564_432d660bed35(i1) ) {
								Hello o1 = map_Namaste_to_Hello_3af870c5_f83f_5b95_d564_432d660bed35(i1);
								System.out.println( "DirectMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof Namaste ) {
					Namaste i1 = (Namaste) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "Bonjour".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_Namaste_to_Bonjour_4f6a15d1_ce0a_15b2_4f6b_8e76908dd1c7(i1) ) {
								Bonjour o1 = map_Namaste_to_Bonjour_4f6a15d1_ce0a_15b2_4f6b_8e76908dd1c7(i1);
								System.out.println( "DirectMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof Hello ) {
					Hello i1 = (Hello) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "Bonjour".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_Hello_to_Bonjour_ef590b70_b120_905a_67dd_3853023db3b5(i1) ) {
								Bonjour o1 = map_Hello_to_Bonjour_ef590b70_b120_905a_67dd_3853023db3b5(i1);
								System.out.println( "DirectMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof Bonjour ) {
					Bonjour i1 = (Bonjour) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "Hello".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_Bonjour_to_Hello_09b590a0_b1a3_c38b_1674_744766af192f(i1) ) {
								Hello o1 = map_Bonjour_to_Hello_09b590a0_b1a3_c38b_1674_744766af192f(i1);
								System.out.println( "DirectMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof Bonjour ) {
					Bonjour i1 = (Bonjour) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "Namaste".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_Bonjour_to_Namaste_cdd75990_a765_dd89_7fe5_9dd3a5d9c4a9(i1) ) {
								Namaste o1 = map_Bonjour_to_Namaste_cdd75990_a765_dd89_7fe5_9dd3a5d9c4a9(i1);
								System.out.println( "DirectMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}
				if( interactionRoot instanceof Hello ) {
					Hello i1 = (Hello) interactionRoot;
					
						if(  !(interactionRoot instanceof NetworkPacket) || "Namaste".equals(((NetworkPacket) interactionRoot).get_packetType())  ) {
	
							if( isGuardConditionMet_Hello_to_Namaste_713ac5d1_f9c2_4f97_6ec0_449bfb12e09b(i1) ) {
								Namaste o1 = map_Hello_to_Namaste_713ac5d1_f9c2_4f97_6ec0_449bfb12e09b(i1);
								System.out.println( "DirectMapper: Sending interaction: " + o1 );
								o1.sendInteraction( getRTI(), getMinTSOTimestamp() );
							}
							
							interactionMapped = true;
						}
						
						
				}

				if( !interactionMapped ) {
	          		System.out.println( "DirectMapper: Received unknown interaction: " + interactionRoot );
	           	}
	        }

	        currentTime = getCurrentTime() + 1 + STEP_EPSILON;
	        AdvanceTimeRequest newATR = new AdvanceTimeRequest( currentTime );
	        putAdvanceTimeRequest( newATR );
	        
	        atr.requestSyncEnd();
	        atr = newATR;
	    }
	}

	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
	    System.out.println( "DirectMapper federate starting" );
	    try {
	    	DirectMapper mapperFed = new DirectMapper( args );
	        mapperFed.execute();
	    } catch ( Exception e ) {
	        System.err.println( "Exception caught: " + e.getMessage() );
	        e.printStackTrace();
	    }
	}

}
