
/*
 * Copyright (c) 2008, Institute for Software Integrated Systems, Vanderbilt University
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 *
 * IN NO EVENT SHALL THE VANDERBILT UNIVERSITY BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE VANDERBILT
 * UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * THE VANDERBILT UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE VANDERBILT UNIVERSITY HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 * @author Himanshu Neema
 * @author Harmon Nine
 */

// This code has been generated by the C2W code generator.
// Do not edit manually!

/*
 * 	NOTE:  ALL "if" STATEMENTS IN THIS CODE THAT HAD THE FORM:
 *
 *  if (condition) statement;
 *
 *	OR
 *
 *  if (condition) statement1;
 *  else           statement2;
 *
 *  HAVE BEEN CONVERTED TO THE FORMS:
 *
 *  if (condition) {
 *		statement;
 *	}
 *
 *	AND
 *
 *  if (condition) {
 *		statement1;
 *	} else {
 *		statement2;
 *	}
 *
 *	RESPECTIVELY.  THIS IS BECAUSE THE OMNET DEBUGGER APPEARS TO HAVE A PROBLEM
 *  WITH THE NON-BRACED FORMS OF THE IF STATEMENT.  *PLEASE* DO NOT CHANGE IT BACK.
 *  -- H.S.N.
 *
 */

#ifndef _StartDNSPoisoningAttack_CLASS
#define _StartDNSPoisoningAttack_CLASS

#include "AttacksNotYetImplemented.hpp"
#include "C2WException.hpp"


class StartDNSPoisoningAttack : public AttacksNotYetImplemented {

public:
	typedef AttacksNotYetImplemented Super;
	typedef boost::shared_ptr< StartDNSPoisoningAttack > SP;

	static StringVector get_parameter_names() {
		return getDatamemberNames();
	}

	static StringVector get_all_parameter_names() {
		return getAllDatamemberNames();
	}

	StartDNSPoisoningAttack( void ) { }
	
	static SP create( void ) { return SP( new StartDNSPoisoningAttack ); }

private:
	
	
	static int &get_affectedHost_handle_var( void ) {
		static int affectedHost_handle;
		return affectedHost_handle;
	}
	static int &get_dnsHost_handle_var( void ) {
		static int dnsHost_handle;
		return dnsHost_handle;
	}
	static int &get_listenerHost_handle_var( void ) {
		static int listenerHost_handle;
		return listenerHost_handle;
	}
	
public:
	
	
	static int get_affectedHost_handle( void ) { return get_affectedHost_handle_var(); }
	static int get_dnsHost_handle( void ) { return get_dnsHost_handle_var(); }
	static int get_listenerHost_handle( void ) { return get_listenerHost_handle_var(); }
	


private:
	static int &getHandle( void ) {
		static int handle;
		return handle;
	}

public:
	static int get_handle( void ) { return getHandle(); }
	static std::string get_class_name( void ) { return "StartDNSPoisoningAttack"; }

private:
	static StringVector &getDatamemberNames( void ) {
		static StringVector datamemberNames;
		return datamemberNames;
	}

	static StringVector &getAllDatamemberNames( void ) {
		static StringVector allDatamemberNames;
		return allDatamemberNames;
	}



private:

	static InteractionRoot::SP factory( void ) {
		return InteractionRoot::SP( new StartDNSPoisoningAttack() );
	}


	static std::string &getInitErrorMessage( void ) {
		static std::string initErrorMessage( "Error:  StartDNSPoisoningAttack:  could not initialize:  " );
		return initErrorMessage;
	}

protected:
	static void init( RTI::RTIambassador *rti );
	
private:
	static bool &getIsPublished( void ) {
		static bool isPublished = false;
		return isPublished;
	}
	
	static std::string &getPublishErrorMessage( void ) {
		static std::string publishErrorMessage = "Error:  StartDNSPoisoningAttack:  could not publish:  ";
		return publishErrorMessage;
	}
	
public:
	static void publish( RTI::RTIambassador *rti );
	
private:
	static std::string &getUnpublishErrorMessage( void ) {
		static std::string unpublishErrorMessage = "Error:  StartDNSPoisoningAttack:  could not unpublish:  ";
		return unpublishErrorMessage;
	}

public:
	static void unpublish( RTI::RTIambassador *rti );

private:
	static bool &getIsSubscribed( void ) {
		static bool isSubscribed = false;
		return isSubscribed;
	}
	static std::string &getSubscribeErrorMessage( void ) {
		static std::string subscribedErrorMessage = "Error:  StartDNSPoisoningAttack:  could not subscribe:  ";
		return subscribedErrorMessage;
	}

public:
	static void subscribe( RTI::RTIambassador *rti );
		
private:
	static std::string getUnsubscribeErrorMessage( void ) {
		static std::string unsubscribeErrorMessage = "Error:  StartDNSPoisoningAttack:  could not unsubscribe:  ";
		return unsubscribeErrorMessage;
	}
	
public:
	static void unsubscribe( RTI::RTIambassador *rti );
	
	static bool static_init( void );
	
	static bool match( int handle ) { return handle == get_handle(); }

	virtual int getClassHandle( void ) const { return get_handle(); }
	virtual std::string getClassName( void ) const { return get_class_name(); }
	virtual StringVector getParameterNames( void ) const { return get_parameter_names(); }
	virtual StringVector getAllParameterNames( void ) const { return get_all_parameter_names(); }

	virtual void publishInteraction( RTI::RTIambassador *rti ) { publish( rti ); }
	virtual void subscribeInteraction( RTI::RTIambassador *rti ) { subscribe( rti ); }

	virtual InteractionRoot::SP clone( void ) {
		return InteractionRoot::SP(  new StartDNSPoisoningAttack( *this )  );
	}







private:
	
	
	std::string _affectedHost;
	
	std::string _dnsHost;
	
	std::string _listenerHost;
	
public:
		
	void set_affectedHost( const std::string & affectedHost ) { _affectedHost = affectedHost; }
	const std::string & get_affectedHost( void ) const { return _affectedHost; }
	
	void set_dnsHost( const std::string & dnsHost ) { _dnsHost = dnsHost; }
	const std::string & get_dnsHost( void ) const { return _dnsHost; }
	
	void set_listenerHost( const std::string & listenerHost ) { _listenerHost = listenerHost; }
	const std::string & get_listenerHost( void ) const { return _listenerHost; }
	


	StartDNSPoisoningAttack( const RTI::ParameterHandleValuePairSet &datamemberMap ) : Super( datamemberMap ) { }
	
	StartDNSPoisoningAttack( const RTI::ParameterHandleValuePairSet &datamemberMap, const RTIfedTime &logicalTime ) : Super( datamemberMap, logicalTime ) { }
	
	
public:
	TypeMedley getParameter( const std::string &datamemberName ) const {
		
		
		if ( "affectedHost" == datamemberName ) {
			return TypeMedley( get_affectedHost() );
		}
		else if ( "dnsHost" == datamemberName ) {
			return TypeMedley( get_dnsHost() );
		}
		else if ( "listenerHost" == datamemberName ) {
			return TypeMedley( get_listenerHost() );
		} else {
			return Super::getParameter( datamemberName );
		}
	}
	
	TypeMedley getParameter( int datamemberHandle ) const {
		
		
		if ( get_affectedHost_handle() == datamemberHandle ) {
			return TypeMedley( get_affectedHost() );
		}
		else if ( get_dnsHost_handle() == datamemberHandle ) {
			return TypeMedley( get_dnsHost() );
		}
		else if ( get_listenerHost_handle() == datamemberHandle ) {
			return TypeMedley( get_listenerHost() );
		} else {
			return Super::getParameter( datamemberHandle );
		}
	}

protected:
	virtual bool setParameterAux( int param_handle, const std::string &val ) {
		bool retval = true;		
		
		
		if ( param_handle == get_affectedHost_handle() ) {
			set_affectedHost(  TypeMedley( val )  );
		}
		else if ( param_handle == get_dnsHost_handle() ) {
			set_dnsHost(  TypeMedley( val )  );
		}
		else if ( param_handle == get_listenerHost_handle() ) {
			set_listenerHost(  TypeMedley( val )  );
		} else {
			retval = Super::setParameterAux( param_handle, val );
		}
		return retval;
	}
	
	virtual bool setParameterAux( const std::string &datamemberName, const std::string &val ) {
		bool retval = true;
		
		
		if ( "affectedHost" == datamemberName ) {
			set_affectedHost(  TypeMedley( val )  );
		}
		else if ( "dnsHost" == datamemberName ) {
			set_dnsHost(  TypeMedley( val )  );
		}
		else if ( "listenerHost" == datamemberName ) {
			set_listenerHost(  TypeMedley( val )  );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}
		
		return retval;
	}
	
	virtual bool setParameterAux( const std::string &datamemberName, const TypeMedley &val ) {
		bool retval = true;
		
		
		if ( "affectedHost" == datamemberName ) {\
			set_affectedHost( val );
		}
		else if ( "dnsHost" == datamemberName ) {\
			set_dnsHost( val );
		}
		else if ( "listenerHost" == datamemberName ) {\
			set_listenerHost( val );
		} else {
			retval = Super::setParameterAux( datamemberName, val );
		}
		
		return retval;
	}

	virtual ParameterHandleValuePairSetSP createDatamemberHandleValuePairSet( RTI::ULong count );

	virtual ParameterHandleValuePairSetSP createDatamemberHandleValuePairSet( ) {
		return createDatamemberHandleValuePairSet( 0 );
	}
	
	
};

typedef StartDNSPoisoningAttack::SP StartDNSPoisoningAttackSP;

static bool call_StartDNSPoisoningAttack_static_init = StartDNSPoisoningAttack::static_init();

std::ostream &operator<<( std::ostream &os, StartDNSPoisoningAttack::SP entitySP );
std::ostream &operator<<( std::ostream &os, const StartDNSPoisoningAttack &entity );
#endif
